import { chromium } from '@playwright/test';
const b = await chromium.launch({ headless: true });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE_ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGE_ERR', String(e)));
const responses = [];
p.on('response', (r) => { if (r.url().includes('/api/config')) responses.push(r); });
await p.goto('http://127.0.0.1:4391/');
await p.getByRole('button', { name: /模型设置/ }).click();
const dialog = p.getByRole('dialog');
await dialog.waitFor();
await dialog.getByRole('button', { name: '新增 Provider' }).click();
await dialog.getByRole('textbox', { name: 'Provider 名称' }).fill('acme');
await dialog.getByRole('textbox', { name: '服务地址' }).fill('https://api.example.com/v1');
await dialog.getByRole('textbox', { name: 'API 密钥' }).fill('sk-placeholder-0123456789');
await dialog.getByRole('textbox', { name: '模型别名 1' }).fill('acme/sonnet');
await dialog.getByRole('textbox', { name: '模型 ID 1' }).fill('claude-sonnet-4-5');
await dialog.getByRole('button', { name: '保存目录' }).click();
await p.waitForTimeout(1500);
for (const r of responses) console.log('RESP', r.request().method(), r.url(), r.status(), (await r.text()).slice(0, 300));
const err = await dialog.locator('.inline-error').allTextContents();
console.log('INLINE_ERROR', JSON.stringify(err));
await p.screenshot({ path: '/tmp/dbg-editor.png' });
await b.close();
